### ISSUE TITLE
Will not find FF14 and start up hunt app

### ISSUE THREAD

**Issue by Mortiebutana** [krvi/XIV-Hunt#3]
Why is this happening every time i try to start it up???

?
[
![hunts](https://user-images.githubusercontent.com/39360133/40156189-e05d5050-5965-11e8-98d3-e7c7eb99352c.png)
](url)

**Comment by krvi** [comment]
I regret the late reply. I have added a log view, in 4.3.2, that should help identify issues where signatures are not found, which I suspect is the case here. If you still have this issue, you can open the log view by pressing the LOG icon beside the cog-wheel/settings icon. If you could share that log with me, it may help identify the issue.
